# Generated by Django 4.2.30 on 2026-06-24 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


def ensure_schema(apps, schema_editor):
    """Create the dedicated survey schema if absent (Postgres only).

    Tables are created with search_path=survey, so the schema must exist first.
    Making it part of this migration means `migrate` works on a clean DB (incl.
    the test DB) without a manual `CREATE SCHEMA` step. No-op on SQLite.
    """
    if schema_editor.connection.vendor != "postgresql":
        return
    from django.conf import settings
    schema = getattr(settings, "SURVEY_DB_SCHEMA", "survey")
    schema_editor.execute(f'CREATE SCHEMA IF NOT EXISTS "{schema}";')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(ensure_schema, migrations.RunPython.noop),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('response_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(choices=[('director', 'Director'), ('teacher', 'Teacher'), ('secretariat', 'Secretariat'), ('parent', 'Parent'), ('inspector', 'Inspector')], max_length=20)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('email_client', 'Email Client'), ('inapp', 'Inapp'), ('gads', 'Gads'), ('fb', 'Fb'), ('other', 'Other')], default='web', max_length=20)),
                ('status', models.CharField(choices=[('partial', 'Partial'), ('completed', 'Completed')], default='partial', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wave', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'survey_responses',
                'indexes': [models.Index(fields=['path', 'status'], name='survey_resp_path_e5f8f2_idx'), models.Index(fields=['channel'], name='survey_resp_channel_9f6e64_idx'), models.Index(fields=['wave'], name='survey_resp_wave_0f4d9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveyEmail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('opted_in_at', models.DateTimeField(auto_now_add=True)),
                ('wave', models.CharField(max_length=10)),
                ('crm_synced', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'survey_emails',
                'indexes': [models.Index(fields=['crm_synced'], name='survey_emai_crm_syn_2e5bbb_idx')],
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=40)),
                ('value', models.JSONField()),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.surveyresponse')),
            ],
            options={
                'db_table': 'survey_answers',
            },
        ),
        migrations.CreateModel(
            name='FreetextModeration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewer', models.CharField(blank=True, max_length=120)),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moderation', to='survey.surveyanswer')),
            ],
            options={
                'db_table': 'survey_freetext_moderation',
            },
        ),
        migrations.AddIndex(
            model_name='surveyanswer',
            index=models.Index(fields=['question_id'], name='survey_answ_questio_9b5bb0_idx'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('response', 'question_id', 'value'), name='uniq_answer_atom'),
        ),
        migrations.AddIndex(
            model_name='freetextmoderation',
            index=models.Index(fields=['status'], name='survey_free_status_e1ff6e_idx'),
        ),
    ]
